- id: prevent-dangling-todos
  name: prevent dangling todos
  description: Check for TODO/FIXME comments without ticket references from any issue tracker (Jira, GitHub, Linear, etc.). Supports multiple prefixes and various file types.
  entry: prevent-dangling-todos
  language: python
  types: [text]
  exclude: '^\.pre-commit-config\.yaml$'
  args: []
  always_run: true
